### ISSUE TITLE
.babelrc is included in npm installed package

### ISSUE THREAD

**Issue by mucsi96** [vgabor/redux-array#1]
I got an error in react-native because `.babelrc` is included in installed npm package

```
TransformError: /Users/igor/repo/client/node_modules/redux-array/lib/index.js: 
Couldn't find preset "es2015" relative to directory "/Users/igor/repo/client/node_modules/redux-array"
```

**Comment by vgabor** [comment]
I think e0c2d4f04cda913e432b3e30191182b980ff4881 will  solve it, I've pushed out the new npm package.

I haven't got any react-native application to see if it works, could you please confirm that it solved the problem?

**Comment by mucsi96** [comment]
Wow! That was very fast! Thanks you! The exception is gone 🎉 
May be you can ignore the test files as well.

Köszönöm!
